### ISSUE TITLE
Support custom path for sphinx-build

### ISSUE THREAD

**Issue by bachp** [GaretJax/sphinx-autobuild#58]
Currently `sphinx-autobuild`  expects `sphinx-build` to be in `PATH`.

One way to support a custom path would be to honor the `SPHINXBUILD` environment variable.

**Comment by superwhoopy** [comment]
A side-effect is that if `sphinx-autobuild` is installed in a virtualenv, it cannot be called "directly"' for instance if your root Makefile defines this targe:

```make
livehtml:
   $(VIRTUALENV_PATH)/bin/sphinx-autobuild -b html $(DOC_SRC) $(DOC_BUILD)
```

it will try to call `sphinx-build` from PATH - and ultimately fail if Sphinx is only installed in the virtualenv.

I've made a (rather stupid) patch, where I call the Sphinx API directly rather than using `Popen()`, if you're interested.

**Comment by rowanG077** [comment]
I have implemented this feature: https://github.com/rowanG077/sphinx-multibuild

**Comment by pradyunsg** [comment]
Sounds like a good idea!
