### ISSUE TITLE
sphinx-autobuild isn't accessible from command line after installation

### ISSUE THREAD

**Issue by symonsoft** [GaretJax/sphinx-autobuild#66]
sphinx-autobuild isn't accessible from command line after installation with pip:

    $ sphinx-autobuild
    sphinx-autobuild: command not found

Ubuntu 16.04

**Comment by pradyunsg** [comment]
You should've seen a warning from pip if you have a recent-enough version of pip. Otherwise, please debug the issue with your `PATH` environment variable.

I'm gonna close this since I'm pretty sure anyone with a recent-enough pip version should see the warning that I implemented in https://github.com/pradyunsg/pip/commit/fc7ca264892767454b166d0fc001a6ca95bde22e.
